import { ThemeProvider } from "@/components/theme-provider";
import {Inter} from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import FloatingShapes from "@/components/floating-shapes";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "./ConvexClientProvider";

const inter=Inter({subsets:["latin"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className}`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
             <ClerkProvider>
            <ConvexClientProvider>
           
            <Header/>
            <main className="bg-slate-900 min-h-[2000px] text-white overflow-x-hidden">
               <FloatingShapes/>
               <Toaster richColors/>
               {children}</main>
               </ConvexClientProvider>
               </ClerkProvider>
          </ThemeProvider>
      </body>
    </html>
  );
}
